### ISSUE TITLE
Can't delete or analyze pcap file anymore

### ISSUE THREAD

**Issue by kuipers-axon** [ebu/pi-list#78] opened 2020-02-17 08:58 UTC
Hi, Today we wanted to remove a pcap from the ebu-list tool. But we got the message that deletion has failed. From the Docker logs I don't see any error lines while deleting a pcap. Are there any known issues with this problem? The pcap files look like they are in some kind of database structure. So I think I can not just delete the pcap by hand.

Sinds the time we have the problem of deleting the files we also can't analyze newly uploaded pcap files anymore.

Below is the point where the last pcap upload was working and suddenly stopped. Maybe this gives some pointers.

```
influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:54:56 +0000] "POST /write?db=LIST HTTP/1.1" 204 0 "-" "cpprestsdk/2.10.2" 954a1e18-4f31-11ea-a1bb-000000000000 3473241
influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:55:00 +0000] "POST /write?db=LIST HTTP/1.1" 204 0 "-" "cpprestsdk/2.10.2" 977f6857-4f31-11ea-a1bc-000000000000 3629021
influxdb_1     | [I] 2020-02-14T13:55:04Z Retention policy shard deletion check commencing. service=retention
influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:55:04 +0000] "POST /write?db=LIST HTTP/1.1" 204 0 "-" "cpprestsdk/2.10.2" 99ee496a-4f31-11ea-a1bd-000000000000 4662841
influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:55:10 +0000] "POST /write?db=LIST HTTP/1.1" 500 20 "-" "cpprestsdk/2.10.2" 9ddbe297-4f31-11ea-a1be-000000000000 19813051
influxdb_1     | [E] 2020-02-14T13:55:33Z [500] - "timeout" service=httpd



list_server_1  | 2020-02-17T08:48:34.124Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap/06b87190-5161-11ea-926e-0b306f5eadd0/streams HTTP/1.0 304 - - 14.059 ms 
list_server_1  | 2020-02-17T08:48:34.129Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap/06b87190-5161-11ea-926e-0b306f5eadd0 HTTP/1.0 304 - - 20.730 ms 
list_server_1  | 2020-02-17T08:48:34.161Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap/06b87190-5161-11ea-926e-0b306f5eadd0 HTTP/1.0 304 - - 27.133 ms 
rabbitmq_1     | 2020-02-17 08:48:38.889 [info] <0.925.0> accepting Web MQTT connection <0.925.0> (10.4.224.102:59788 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:38.903 [info] <0.929.0> accepting Web MQTT connection <0.929.0> (10.4.224.102:59790 -> 192.168.32.2:15675)
list_server_1  | 2020-02-17T08:48:38.932Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/workflow HTTP/1.0 304 - - 3.973 ms 
rabbitmq_1     | 2020-02-17 08:48:38.932 [info] <0.925.0> MQTT vhost picked using plugin configuration or default
rabbitmq_1     | 2020-02-17 08:48:38.932 [info] <0.929.0> MQTT vhost picked using plugin configuration or default
list_server_1  | 2020-02-17T08:48:38.950Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/live/sources/ HTTP/1.0 200 2 - 19.719 ms 
list_server_1  | 2020-02-17T08:48:38.951Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap HTTP/1.0 304 - - 26.099 ms 
list_server_1  | 2020-02-17T08:48:39.006Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/meta/version HTTP/1.0 304 - - 2.236 ms 
rabbitmq_1     | 2020-02-17 08:48:41.033 [info] <0.925.0> closing Web MQTT connection <0.925.0> (10.4.224.102:59788 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:41.035 [info] <0.929.0> closing Web MQTT connection <0.929.0> (10.4.224.102:59790 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:41.037 [error] <0.937.0> Supervisor {<0.937.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(direct, <0.933.0>, <<"10.4.224.102:59788 -> 192.168.32.2:15675">>) at undefined exit with reason shutdown in context shutdown_error
list_server_1  | 2020-02-17T08:48:41.051Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/live/streams/ HTTP/1.0 200 2 - 5.319 ms 
list_server_1  | 2020-02-17T08:48:42.038Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/user HTTP/1.0 304 - - 2.421 ms 
list_server_1  | 2020-02-17T08:48:43.642Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap HTTP/1.0 304 - - 8.404 ms 
list_server_1  | 2020-02-17T08:48:43.650Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/analysis_profile HTTP/1.0 304 - - 17.504 ms 
list_server_1  | 2020-02-17T08:48:43.677Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/meta/version HTTP/1.0 304 - - 1.989 ms 
rabbitmq_1     | 2020-02-17 08:48:44.721 [info] <0.991.0> accepting Web MQTT connection <0.991.0> (10.4.224.102:59798 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:44.723 [info] <0.991.0> MQTT vhost picked using plugin configuration or default
list_server_1  | 2020-02-17T08:48:44.726Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/workflow HTTP/1.0 304 - - 3.337 ms 
rabbitmq_1     | 2020-02-17 08:48:45.833 [info] <0.991.0> closing Web MQTT connection <0.991.0> (10.4.224.102:59798 -> 192.168.32.2:15675)
list_server_1  | 2020-02-17T08:48:45.855Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap HTTP/1.0 304 - - 9.091 ms 
list_server_1  | 2020-02-17T08:48:45.863Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/analysis_profile HTTP/1.0 304 - - 19.729 ms 
```

![image](https://user-images.githubusercontent.com/59870451/74637140-b1863500-5169-11ea-94a4-e777bb78b369.png)

**Comment by pedro-alves-ferreira** [comment] 2020-02-17 10:40
Hello,

We have never seen anything like that, unless in cases where the disk got full.
If that is not the case, and you don't mind losing the pcaps in the database, the best solutions is to do:

> cd <dir where the docker-compose.yml file is>
> docker-compose down
> docker system prune --volumes

This will clean all the docker storage.

Let me know if that is a good solution for you. If not, we'll try to dig further.

Best regards,

Pedro Ferreira


On 17/02/20 08:58, kuipers-axon wrote:

Hi, Today we wanted to remove a pcap from the ebu-list tool. But we got the message that deletion has failed. From the Docker logs I don't see any error lines while deleting a pcap. Are there any known issues with this problem? The pcap files look like they are in some kind of database structure. So I think I can not just delete the pcap by hand.

Sinds the time we have the problem of deleting the files we also can't analyze newly uploaded pcap files anymore.

Below is the point where the last pcap upload was working and suddenly stopped. Maybe this gives some pointers.

influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:54:56 +0000] "POST /write?db=LIST HTTP/1.1" 204 0 "-" "cpprestsdk/2.10.2" 954a1e18-4f31-11ea-a1bb-000000000000 3473241
influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:55:00 +0000] "POST /write?db=LIST HTTP/1.1" 204 0 "-" "cpprestsdk/2.10.2" 977f6857-4f31-11ea-a1bc-000000000000 3629021
influxdb_1     | [I] 2020-02-14T13:55:04Z Retention policy shard deletion check commencing. service=retention
influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:55:04 +0000] "POST /write?db=LIST HTTP/1.1" 204 0 "-" "cpprestsdk/2.10.2" 99ee496a-4f31-11ea-a1bd-000000000000 4662841
influxdb_1     | [httpd] 192.168.32.5 - - [14/Feb/2020:13:55:10 +0000] "POST /write?db=LIST HTTP/1.1" 500 20 "-" "cpprestsdk/2.10.2" 9ddbe297-4f31-11ea-a1be-000000000000 19813051
influxdb_1     | [E] 2020-02-14T13:55:33Z [500] - "timeout" service=httpd



list_server_1  | 2020-02-17T08:48:34.124Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap/06b87190-5161-11ea-926e-0b306f5eadd0/streams HTTP/1.0 304 - - 14.059 ms
list_server_1  | 2020-02-17T08:48:34.129Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap/06b87190-5161-11ea-926e-0b306f5eadd0 HTTP/1.0 304 - - 20.730 ms
list_server_1  | 2020-02-17T08:48:34.161Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap/06b87190-5161-11ea-926e-0b306f5eadd0 HTTP/1.0 304 - - 27.133 ms
rabbitmq_1     | 2020-02-17 08:48:38.889 [info] <0.925.0> accepting Web MQTT connection <0.925.0> (10.4.224.102:59788 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:38.903 [info] <0.929.0> accepting Web MQTT connection <0.929.0> (10.4.224.102:59790 -> 192.168.32.2:15675)
list_server_1  | 2020-02-17T08:48:38.932Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/workflow HTTP/1.0 304 - - 3.973 ms
rabbitmq_1     | 2020-02-17 08:48:38.932 [info] <0.925.0> MQTT vhost picked using plugin configuration or default
rabbitmq_1     | 2020-02-17 08:48:38.932 [info] <0.929.0> MQTT vhost picked using plugin configuration or default
list_server_1  | 2020-02-17T08:48:38.950Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/live/sources/ HTTP/1.0 200 2 - 19.719 ms
list_server_1  | 2020-02-17T08:48:38.951Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap HTTP/1.0 304 - - 26.099 ms
list_server_1  | 2020-02-17T08:48:39.006Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/meta/version HTTP/1.0 304 - - 2.236 ms
rabbitmq_1     | 2020-02-17 08:48:41.033 [info] <0.925.0> closing Web MQTT connection <0.925.0> (10.4.224.102:59788 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:41.035 [info] <0.929.0> closing Web MQTT connection <0.929.0> (10.4.224.102:59790 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:41.037 [error] <0.937.0> Supervisor {<0.937.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(direct, <0.933.0>, <<"10.4.224.102:59788 -> 192.168.32.2:15675">>) at undefined exit with reason shutdown in context shutdown_error
list_server_1  | 2020-02-17T08:48:41.051Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/live/streams/ HTTP/1.0 200 2 - 5.319 ms
list_server_1  | 2020-02-17T08:48:42.038Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/user HTTP/1.0 304 - - 2.421 ms
list_server_1  | 2020-02-17T08:48:43.642Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap HTTP/1.0 304 - - 8.404 ms
list_server_1  | 2020-02-17T08:48:43.650Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/analysis_profile HTTP/1.0 304 - - 17.504 ms
list_server_1  | 2020-02-17T08:48:43.677Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/meta/version HTTP/1.0 304 - - 1.989 ms
rabbitmq_1     | 2020-02-17 08:48:44.721 [info] <0.991.0> accepting Web MQTT connection <0.991.0> (10.4.224.102:59798 -> 192.168.32.2:15675)
rabbitmq_1     | 2020-02-17 08:48:44.723 [info] <0.991.0> MQTT vhost picked using plugin configuration or default
list_server_1  | 2020-02-17T08:48:44.726Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/workflow HTTP/1.0 304 - - 3.337 ms
rabbitmq_1     | 2020-02-17 08:48:45.833 [info] <0.991.0> closing Web MQTT connection <0.991.0> (10.4.224.102:59798 -> 192.168.32.2:15675)
list_server_1  | 2020-02-17T08:48:45.855Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap HTTP/1.0 304 - - 9.091 ms
list_server_1  | 2020-02-17T08:48:45.863Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/analysis_profile HTTP/1.0 304 - - 19.729 ms


[image]<https://user-images.githubusercontent.com/59870451/74637140-b1863500-5169-11ea-94a4-e777bb78b369.png>

**Comment by kuipers-axon** [comment] 2020-02-17 15:12
Hi Pedro,

Thanks for your reply! We can do this to make it work again. It's a bit scary that we suddenly can't upload and remove new pcaps anymore. The analysis is also stuck. 

This happened by uploading multiple pcap files and suddenly stopped. If you like to have some kind of logging please let me know. Tomorrow I will fix the container with your solution. Then the logging is removed.

If this problem happens again I will reopen this issue and provide new information (if I have any).

Grtz,
Mark Kuipers

**Comment by pedro-alves-ferreira** [comment] 2020-02-17 15:57
Hi Mark,

You're absolutely right. I'm trying to reproduce that but to no avail. I'd appreciate if you send me the logs and, should it happen again, to let us know that. If you could detail as much as possible whatever steps led to that, it would be great.

Regards,

Pedro

No dia 17/02/2020, às 15:12, kuipers-axon <notifications@github.com> escreveu:

﻿

Hi Pedro,

Thanks for your reply! We can do this to make it work again. It's a bit scary that we suddenly can't upload and remove new pcaps anymore. The analysis is also stuck.

This happened by uploading multiple pcap files and suddenly stopped. If you like to have some kind of logging please let me know. Tomorrow I will fix the container with your solution. Then the logging is removed.

If this problem happens again I will reopen this issue and provide new information (if I have any).

Grtz,
Mark Kuipers

**Comment by kuipers-axon** [comment] 2020-02-25 08:53
Hi Pedro,

Yesterday we fixed the docker container by down and up. Eventually, we had to restart system because the influxdb container was stuck. Probably that could cause the problem that we couldn't remove the files anymore.

I checked the logging and there were no error in the logging regarding this issue. I added the log to this issue.
[docker-compose-log.txt](https://github.com/ebu/pi-list/files/4248945/docker-compose-log.txt)

For now it's working again.

Grtz,
Mark Kuipers

**Comment by pedro-alves-ferreira** [comment] 2020-02-25 10:52
Hi Mark,

Thanks for getting back to me.

That looks like a plausible reason for LIST to stop working. It may have gotten stuck while trying to delete the data set from influxdb.

I will look at the logs and see if I can get anything from that and look for any issue with influxdb.

Best regards,

Pedro

**Closed** 2021-01-26 11:25 UTC
