### ISSUE TITLE
API call PUT /api/pcap fails if no active Websocket is present

### ISSUE THREAD

**Issue by haron** [ebu/pi-list#137] opened 2021-11-08 09:53 UTC
API call PUT /api/pcap fails when there is no browser with an open Websocket to send a message to.

Steps to reproduce:
1. start the the environment with docker-compose (`docker-compose -f docs/docker-compose.yml up`)
2. create a user via the API call `/user/register`
2. login via the API `/auth/login`, get the token
3. make an authenticated PUT request to the API (header `Authorization: Bearer {my_token}`)
4. see docker-compose logs

Error in logs:

```listserver_1  | 2021-11-08T09:43:30.431759032Z 2021-11-08T09:43:30.428Z [express-middleware] error: TypeError: Cannot read property 'forEach' of undefined
listserver_1  | 2021-11-08T09:43:30.431810433Z     at WebSocket.sendEventToUser (/app/listwebserver/dist/managers/websocket.js:36:20)
listserver_1  | 2021-11-08T09:43:30.431819933Z     at pcapFormatConversion (/app/listwebserver/dist/util/analysis/index.js:83:33)
listserver_1  | 2021-11-08T09:43:30.431828133Z     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  | 2021-11-08T09:43:30.431836334Z     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  | 2021-11-08T09:43:30.431844334Z     at pcapFileAvailableFromReq (/app/listwebserver/dist/util/analysis/index.js:73:9)
listserver_1  | 2021-11-08T09:43:30.431852434Z     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  | 2021-11-08T09:43:30.431860434Z     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  | 2021-11-08T09:43:30.431868334Z     at /app/listwebserver/dist/api/pcap.js:60:5
listserver_1  | 2021-11-08T09:43:30.431876035Z     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  | 2021-11-08T09:43:30.431883935Z     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  | 2021-11-08T09:43:30.431891835Z     at Immediate._onImmediate (/app/listwebserver/node_modules/multer/lib/make-middleware.js:53:37)
listserver_1  | 2021-11-08T09:43:30.431899835Z     at processImmediate (internal/timers.js:463:21)
listserver_1  | 2021-11-08T09:43:30.451529042Z 2021-11-08T09:43:30.447Z [rest-api] info: ::ffff:172.19.0.5 - PUT /api/pcap HTTP/1.0 500 139 - 154.743 ms

listserver_1  | 2021-11-08T09:43:30.451610444Z Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
listserver_1  | 2021-11-08T09:43:30.451623544Z     at ServerResponse.setHeader (_http_outgoing.js:530:11)
listserver_1  | 2021-11-08T09:43:30.451650045Z     at ServerResponse.header (/app/listwebserver/node_modules/express/lib/response.js:771:10)
listserver_1  | 2021-11-08T09:43:30.451659545Z     at ServerResponse.send (/app/listwebserver/node_modules/express/lib/response.js:170:12)
listserver_1  | 2021-11-08T09:43:30.451667645Z     at ServerResponse.json (/app/listwebserver/node_modules/express/lib/response.js:267:15)
listserver_1  | 2021-11-08T09:43:30.451690346Z     at ServerResponse.send (/app/listwebserver/node_modules/express/lib/response.js:158:21)
listserver_1  | 2021-11-08T09:43:30.451699146Z     at apiErrorHandler (/app/listwebserver/dist/util/express-middleware.js:27:28)
listserver_1  | 2021-11-08T09:43:30.451707046Z     at Layer.handle_error (/app/listwebserver/node_modules/express/lib/router/layer.js:71:5)
listserver_1  | 2021-11-08T09:43:30.451714646Z     at trim_prefix (/app/listwebserver/node_modules/express/lib/router/index.js:315:13)
listserver_1  | 2021-11-08T09:43:30.451722147Z     at /app/listwebserver/node_modules/express/lib/router/index.js:284:7
listserver_1  | 2021-11-08T09:43:30.451729547Z     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  | 2021-11-08T09:43:30.451737347Z     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  | 2021-11-08T09:43:30.451744847Z     at Layer.handle_error (/app/listwebserver/node_modules/express/lib/router/layer.js:67:12)
listserver_1  | 2021-11-08T09:43:30.451752447Z     at trim_prefix (/app/listwebserver/node_modules/express/lib/router/index.js:315:13)
listserver_1  | 2021-11-08T09:43:30.451759948Z     at /app/listwebserver/node_modules/express/lib/router/index.js:284:7
listserver_1  | 2021-11-08T09:43:30.451767248Z     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  | 2021-11-08T09:43:30.451774648Z     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  | 2021-11-08T09:43:30.451782048Z     at /app/listwebserver/node_modules/express/lib/router/index.js:635:15
listserver_1  | 2021-11-08T09:43:30.451789348Z     at next (/app/listwebserver/node_modules/express/lib/router/index.js:260:14)
listserver_1  | 2021-11-08T09:43:30.451796649Z     at /app/listwebserver/node_modules/express/lib/router/index.js:635:15
listserver_1  | 2021-11-08T09:43:30.451803949Z     at next (/app/listwebserver/node_modules/express/lib/router/index.js:260:14)
listserver_1  | 2021-11-08T09:43:30.451811349Z     at next (/app/listwebserver/node_modules/express/lib/router/route.js:127:14)
listserver_1  | 2021-11-08T09:43:30.451818649Z     at Layer.handle_error (/app/listwebserver/node_modules/express/lib/router/layer.js:67:12)```

**Comment by vasily-v-ryabov** [comment] 2021-11-08 10:19
Hi @pedro-alves-ferreira this issue is reproduced with API version 1.17.6 and 1.16.6 as well.
We have to keep Web UI open and logged in to make our scripts working which partially neglects the idea of this automation.

I think the more relevant crash stack is this one (TypeError message is important):
```
listserver_1  | 2021-11-08T10:16:22.355Z [express-middleware] error: TypeError: Cannot read property 'forEach' of undefined
listserver_1  |     at WebSocket.sendEventToUser (/app/listwebserver/dist/managers/websocket.js:36:20)
listserver_1  |     at pcapFormatConversion (/app/listwebserver/dist/util/analysis/index.js:83:33)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  |     at pcapFileAvailableFromReq (/app/listwebserver/dist/util/analysis/index.js:73:9)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  |     at /app/listwebserver/dist/api/pcap.js:60:5
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  |     at Immediate._onImmediate (/app/listwebserver/node_modules/multer/lib/make-middleware.js:53:37)
listserver_1  |     at processImmediate (internal/timers.js:463:21)
listserver_1  | 2021-11-08T10:16:22.360Z [rest-api] info: ::ffff:192.168.0.5 - PUT /api/pcap HTTP/1.0 500 139 - 2174.329 ms
```

From the logs it looks like the list of open WebSocket connections is empty. But it is interpreted as undefined value. I guess it should be fixed on server side. `forEach` loop should interpret it as empty list and execute no iterations of sending the data back.

Hope this problem is easy to fix for you. We want to publish Python client package for LIST API after we get it working and after we get an approval from our company.

**Comment by vasily-v-ryabov** [comment] 2021-11-08 10:22
We're trying to workaround it with Python package `websocket-client`. But if it's fixed on server side, it will save some time for us and reduce number of dependecies.

**Comment by pedro-alves-ferreira** [comment] 2021-11-08 14:50
Hi!

Thanks for reporting this. I'll try to reproduce it with v2.0.2 and then I'll get back to you.

Regards,

Pedro

**Comment by pedro-alves-ferreira** [comment] 2021-11-08 15:25
It's still in v2.0.2. I'll get that fixed and make a new release later today.

By the way, are you aware of this: https://github.com/bisect-pt/ebu-list-sdk

It's typescript, not Python, but maybe it can help.

**Comment by pedro-alves-ferreira** [comment] 2021-11-08 18:26
Should be fixed in v2.0.3. Please confirm.

Thanks,

Pedro

**Comment by haron** [comment] 2021-11-09 06:19
@pedro-alves-ferreira works as expected. Great, thanks a lot for such a quick reaction.

**Comment by vasily-v-ryabov** [comment] 2021-11-09 09:12
Thanks a lot @pedro-alves-ferreira !

**Closed** 2021-11-09 09:25 UTC
